### ISSUE TITLE
Licence for the code?

### ISSUE THREAD

**Issue by njones** [ehmry/monero#1]
Hello,

There are some sections of the base58 code in this repo that I would like to borrow and/or use for inspiration for some code ([njones/base58](github.com/njones/base58)) that I'm writing (under the MIT license). However I don't see a license for the code in this repo; so that A) I know I can use it and B) I know how to attribute you in the code that I'm developing.

Can you add a license for the code in this repo?

**Comment by ehmry** [comment]
Hey,

I just unlicensed the code, so do as you will. You probably know this already, but Monero base58 encoding is different than Bitcoin base58 (because base58 is a dumb idea).

**Comment by ehmry** [comment]
@njones if you want another Monero/CryptoNote base58 implementations see https://github.com/ehmry/nim-monero/blob/master/monero/base58.nim
